server:
  port: ${PORT:8080}

spring:
  datasource:
    platform: postgres
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/automodelista}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:root}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql